# Generated by Django 4.1.1 on 2022-10-03 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Menyu nomini kiriting...', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Mahsulot nomini kiriting...', max_length=200)),
                ('mahsulot_haqida', models.TextField()),
                ('rasim', models.ImageField(help_text='Mahsulot rasmini kiriting', upload_to='mahsulot/rasmlar')),
                ('narxi', models.IntegerField(help_text='Mahsulot narxini kiriting...')),
                ('turi', models.ForeignKey(help_text='Mahsulot turini kiriting...', on_delete=django.db.models.deletion.CASCADE, to='mahsulot.menyu')),
            ],
        ),
    ]
